[package]
name = "CMbackend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inputbot = "0.5.1"
arboard = "2.1.0"

[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled"]
