[package]
name = "CMui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
inputbot = "0.5.1"

[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled"]